#!/bin/bash

PROPERTIES_FILE="src/main/resources/META-INF/source-code.properties"

getProjectVersion() {
    if [ -f "$propertiesFile" ]; then
        echo $(getPropertyValue "$PROPERTY_PROJECT_VERSION" "$propertiesFile")
    else
        showMessage "info" "Not found the \e[4m$propertiesFile\e[24m version properties file."
        showMessage "fail" "$goal FAILED" true true
        exit 1
    fi
}

setProjectVersion() {
    setPomVersion "$1" "$2"
}

setPomVersion() {
    if $1 ; then
        mvn versions:set -DnewVersion="$2" -DgenerateBackupPoms=false
    else
        {
            mvn versions:set -DnewVersion="$2" -DgenerateBackupPoms=false
        } 1>&-
    fi
}