#!/bin/bash

setProjectVersionInConfigFiles() {
    if $1 ; then
        mvn versions:set -DnewVersion=$2
        mvn versions:commit
    else
        {
            mvn versions:set -DnewVersion=$2
            mvn versions:commit
        } 1>&- 2>&-
    fi
}
